gateway-service:
  timeout-ms: 3000
  failure-rate-threshold: 50
  slow-call-rate-threshold: 50
  slow-call-duration-threshold: 50
  permitted-num-of-calls-in-half-open-state: 10
  sliding-window-size: 10
  min-number-of-calls: 10
  wait-duration-in-open-state: 60000

server:
  port: 9090

spring:
  application:
    name: gateway-service
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
    gateway:
      discovery:
        locator:
          enabled: false
          lowerCaseServiceId: true
      routes:
        - id: subscription-service
          uri: lb://subscription-service
          predicates:
            - Path=/subscription/**
          filters:
            - RewritePath=/elastic-query-service/(?<path>.*), /$\{path}

        - id: email-service
          uri: lb://email-service
          predicates:
            - Path=/email-service/**
          filters:
            - RewritePath=/email-service/(?<path>.*), /$\{path}

management:
  endpoints:
    web:
      base-path: /actuator
      exposure.include: health, prometheus, gateway
      path-mapping.prometheus: metrics
  endpoint:
    health:
      show-details: always
    prometheus:
      cache.time-to-live: 1ms
    gateway:
      enabled: true
